export const datas = [
  {
    projectTitle: "Tasty-Pizza-App",
    img: "pizza-app.jpg",
    frontEnd: "https://github.com/KALANJIYARAJ/pizza-app-client",
    backEnd: "https://github.com/KALANJIYARAJ/pizza-app-server",
    project: "https://polite-travesseiro-391141.netlify.app",
    tech: ["react.png", "nodejs.png", "mongodb.png"],
    about:
      "This application allows customers to order pizza online, which can be a more convenient and faster option than ordering over the phone.",
  },

  // {
  //   projectTitle: "Polymer-Search-Clone-App",
  //   img: "polymer-app.png",
  //   tech: ["react.png", "nodejs.png", "mongodb.png"],
  //   frontEnd: "https://github.com/KALANJIYARAJ/polymer-search-clone-fd",
  //   backEnd: "https://github.com/KALANJIYARAJ/polymer-search-clone-be",
  //   project: "https://cheery-sable-aa0af6.netlify.app",
  //   about:
  //     "This Polymer Search application is for MS Excel files, which allows users to search by importing and analyzing data from this application.",
  // },

  {
    projectTitle: "Number Guessing Game",
    img: "game.png",
    frontEnd: "https://github.com/KALANJIYARAJ/guessing-number-client",
    backEnd: "https://github.com/KALANJIYARAJ/guessing-number-server",
    project: "https://relaxed-lily-253ddb.netlify.app",
    tech: ["react.png", "nodejs.png", "mongodb.png"],
    about:
      "This game application is to guess a random 4 digits number generated by a computer in the range 1234 – 9876.",
  },

  {
    projectTitle: "Money-Saver-App",
    img: "pic3.png",
    frontEnd: "https://github.com/KALANJIYARAJ/expense-tracker-app-client",
    backEnd: "https://github.com/KALANJIYARAJ/expense-tracker-app-server",
    project: "https://lively-tarsier-82ff10.netlify.app",
    tech: ["react.png", "nodejs.png", "mongodb.png"],
    about:
      "This application helps users track their income and expenses.Such applications can help users maintain their budget and save money.",
  },

  {
    projectTitle: "Raj-Chat-Room",
    img: "raj-chat-room.png",
    frontEnd: "https://github.com/KALANJIYARAJ/chat-app-client",
    backEnd: "https://github.com/KALANJIYARAJ/chat-app-server",
    project: "https://hilarious-blancmange-c06dc3.netlify.app",
    tech: ["react.png", "nodejs.png", "mongodb.png", "socketio.png"],
    about:
      "This application is to allow users to communicate with each other in real-time over the internet.",
  },
];
